### ISSUE TITLE
PowerRanks v2 bug report - mini thread

### ISSUE THREAD

**Issue by vijaypondini** [PowerNetworkHub/PowerRanks#35]
**I'm not a dummy, so I've checked these**
- [yes] I am not using any other permission management plugin
- [yes] I use the latest available version of PowerRanks
- [yes] I am a human

**Describe the bug**
I will continue to report any v2 errors over here in this thread.
Bug/Feature - Plugman support/reload command support.
Attempting to restart the plugin via plugman will fail and make the plugin disabled.
https://mclo.gs/u8AZdMr - In this attempt there was restarting the plugin, then trying to enable it 

**To Reproduce**
1. Get the latest beta available for download. 
2. Get plugman plugin
3. Attempt to restart the plugin using plugman ( /plugman restart powerranks )

**Expected behavior**
The plugin should restart, or a reload command should be available

**Logs**
https://mclo.gs/u8AZdMr same as above

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Server Paper
 - Minecraft 1.17.1
 - PowerRanks v2 beta

**Additional context**
Further bugs/problems I find with v2 will be reported. I hope to help you out :)

**Comment by vijaypondini** [comment]
Number two - Uncertain memory leaks, i've noticed while trying to fetch tablisted commands, on occasion it takes a good few seconds to get them. Briefly checking the tps after shows its overloaded. 
It seems like it's having trouble getting the tab suggestions in the plugin itself, the test server i'm on has lagged entirely simply to check this.

**Comment by benwoo1110** [comment]
Reloading is generally not support by basically all plugins. See https://madelinemiller.dev/blog/problem-with-reload/

**Comment by vijaypondini** [comment]
PowerRanks placeholders do not work in powerchat ( and probably not elsewhere )

Steps to reproduce
--> Get powerranks v2 snapshot 295-bukkit-snapshot 
--> Get powerchat v1.0.0-BETA-4-SNAPSHOT

In powerranks - Ensure you have two ranks with two different weights. In example, moderator could have weight 2, and member could have weight 1

In powerchat - Change nothing but your config of powerchat to have `chat_format: '%powerranks_all_ranks% {name}: {message}'`

Result - Chat format does not work, error is 
![image](https://user-images.githubusercontent.com/70318494/131787328-c3c9b733-6db2-4cb5-a53a-f16ad7cfe4f8.png)


Tested with PlaceholderAPI? Yes
Any chat formatting plugins? Towny, but townychat is removed.

[22:32:57 INFO]: Plugins (24): AuctionHouse, BedrockPlayerManager, BungeeGuard, ClearLag, CoreProtect, Craftconomy3*, DiscordSRV, EconomyShopGUI, FastAsyncWorldEdit (WorldEdit), floodgate, GriefPrevention, InventoryRollback, LiteBans, MyCommand, Parties, PlaceholderAPI, PowerChat, PowerRanks, QuickShop, Spartan, SpartanWebhooks, Towny, Vault, WorldGuard

[22:33:07 INFO]: This server is running Purpur version git-Purpur-1370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdbf59d on ver/1.17.1)
