### ISSUE TITLE
**powerranks problem with chat formatting**

### ISSUE THREAD

**Issue by darlinxpro** [PowerNetworkHub/PowerRanks#36]
**powerranks problem with chat formatting**
line #2 present this in config.yml
chat: {enabled: true, format: '%clans_colored_clan_tag% &l&4**&r%powerranks_prefix%&l&4**[player]&r» %powerranks_chatcolor%[msg]'}
the rank color rgb what I use in the tablist is number #3 
tablist_modification: {enabled: true, format: '&a[%clans_clan_tag%]&r[prefix]&r[player]'}

the problem is because the chat formatting no support the color, actualize plz

**Screenshots**
![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 8_14_2021 2_00_27 PM (2)](https://user-images.githubusercontent.com/88944300/129456432-1e04c8bd-ad3b-41f8-80f6-6a6c405382d5.png)

**Comment by itzJOHv** [comment]
can you give us debug info? such as Server version and PowerRanks version. or just screenshots of these commands:
1. `/ver`
2. `/ver PowerRanks`

**Comment by greatericontop** [comment]
this looks like it is working as intended, what's the issue?

**Comment by darlinxpro** [comment]
> can you give us debug info? such as Server version and PowerRanks version. or just screenshots of these commands:
> 
> 1. `/ver`
> 2. `/ver PowerRanks`

powerranks version 1.9.9R3

**Comment by vijaypondini** [comment]
To top on this, the gradient will work if you don't have powerranks chat formatting, ( i demonstrate here by showing a non-pr formatted chat ( % test cuz we all know % breaks formatting ), and one without

![image](https://user-images.githubusercontent.com/70318494/130753313-20e1e497-6c27-4280-9cca-42dc63c8fa01.png)
