### ISSUE TITLE
Custom to default prefix

### ISSUE THREAD

**Issue by ItzEnderArkail** [PowerNetworkHub/PowerRanks#39]
Sometimes at random times the default prefix shows for users

Purpur 1.16.5
Powerranks 1.9.9R4

Bug:
![image](https://user-images.githubusercontent.com/29746640/132428836-a1bf6211-c087-4a4b-ad14-a92bfb12548d.png)

My custom prefix it's the one showing "Miembro >" and the default one is the "[Member]" one

**Comment by greatericontop** [comment]
Please don't post bug reports without detailed information and before testing and finding a way to reproduce them.

In the meantime, please come to the discord https://discord.gg/rAgBHMB and post your ranks.yml in the support channel

**Comment by ItzEnderArkail** [comment]
> Please don't post bug reports without detailed information and before testing and finding a way to reproduce them.
> 
> In the meantime, please come to the discord https://discord.gg/rAgBHMB and post your ranks.yml in the support channel

i mean how do you reproduce something that happends randomly? there's no way of doing it, and you can check my previous rank.yml in another [issue](https://github.com/svenar-nl/PowerRanks/issues/38) i did

**Comment by itzJOHv** [comment]
> > Please don't post bug reports without detailed information and before testing and finding a way to reproduce them.
> > 
> > In the meantime, please come to the discord https://discord.gg/rAgBHMB and post your ranks.yml in the support channel
> 
> i mean how do you reproduce something that happends randomly? there's no way of doing it, and you can check my previous rank.yml in another [issue](https://github.com/svenar-nl/PowerRanks/issues/38) i did (still the same rank.yml as now)

1. if we can't reproduce the error, we can't fix it.
2. there is no such file called `rank.yml`

**Comment by ItzEnderArkail** [comment]
> > > Please don't post bug reports without detailed information and before testing and finding a way to reproduce them.
> > > In the meantime, please come to the discord https://discord.gg/rAgBHMB and post your ranks.yml in the support channel
> > 
> > 
> > i mean how do you reproduce something that happends randomly? there's no way of doing it, and you can check my previous rank.yml in another [issue](https://github.com/svenar-nl/PowerRanks/issues/38) i did (still the same rank.yml as now)
> 
> 1. if we can't reproduce the error, we can't fix it.
> 2. there is no such file called `rank.yml`

1. just happends randomly
2. i can't upload files for some reason so i had to upload the full text instead in that issue

**Comment by greatericontop** [comment]
Please go to the discord for individual support.

**github issues** only work for reproducable bugs
