### ISSUE TITLE
not saving lang.yml

### ISSUE THREAD

**Issue by swa324** [PowerNetworkHub/PowerRanks#48]
**I'm not a dummy, so I've checked these**
- [x] I am not using any other permission management plugin
- [ ] I use the latest available version of PowerRanks
- [x] I am a human

**It wont save**
I want my rank promotion message to be a little bit diffrent, i also want a diffrent prefix. but no matter how much i try to edit lang.yml, it wont save. there is no error and the plugin reloads successfully.

**Expected behavior**
I expect it to change what i want it to change, but it doesnt work.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Server type [eSpigot]
 - Minecraft Version [e.g. 1.17.1]
 - PowerRanks version [1.10.3]

**Comment by GamerBoss101** [comment]
You don't have the latest version of PowerRanks ( PR 1.10.4)

**Comment by itzJOHv** [comment]
> You don't have the latest version of PowerRanks ( PR 1.10.4)

i like how they ticked "I use the latest available version of PowerRanks" with that
