### ISSUE TITLE
have no idea what this is 

### ISSUE THREAD

**Issue by Zer0-kUn** [PowerNetworkHub/PowerRanks#54]
Hi, im running powerranks (1.10.5r2) on a 1.18.2 server.
It keeps giving this error :java.lang.NullPointerExceptionCannot invoke "nl.svenar.common.structure.PRRank.getWeight()" because "rank" is null
I have no idea what this means or if there is an easy fix for this and since theres some weird stuff going on with the perms and ranks i have no idea if this error that keeps popping up every 3 seconds is the cause of it.

This is the full error and what it says after it in the console: https://www.toptal.com/developers/hastebin/ebolivejih.yaml
Thanks

**Comment by itzJOHv** [comment]
this issue can be solved within the [discord server](https://discord.powerranks.nl)

**Comment by svenar-nl** [comment]
This is indeed a bug [(code)](https://github.com/PowerNetworkHub/PowerRanks/blob/6448480eaf30427aa35e0792b5d454160db1a241/src/main/java/nl/svenar/PowerRanks/Data/TablistManager.java#L149) and will be fixed in the next release

**Comment by Zer0-kUn** [comment]
aight whens next release planned?

**Comment by svenar-nl** [comment]
No release date for the next version is available yet.

**Comment by Zer0-kUn** [comment]
aight thanks o/
