### ISSUE TITLE
Deluxetags/Powerranks

### ISSUE THREAD

**Issue by arsondog** [PowerNetworkHub/PowerRanks#58]
**I'm not a dummy, so I've checked these**
- [T ] I am not using any other permission management plugin
- [ST] I use the latest available version of PowerRanks
- [T ] I am a human

For the second one, I am using the latest supported version. 

**Describe the bug**
I have no chat management plugins and the deluxe tags plugin is hooked to be true yet the deluxe tags aren't showing up. I can't find anything for why this isn't working. I am not sure if this should go to the deluxe tags issue forms or here. There is no error shown in Console when I try to enable the tag. I have even tried to put in the permission node for the tag and it still does not work. 

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Logs**
N/A

**Desktop (please complete the following information):**
 - OS: [Idk what you mean by this]
 - Server type [Bukkit/Spigot]
 - Minecraft Version [1.16.5]
 - PowerRanks version [Latest Supported Version]

**Additional context**
N/A

**If you need anything else, feel free to let me know and I'll try my best to give them to you if possible. Thank you. :) **

**Comment by arsondog** [comment]
Oh. Forgot to mention that I have tried doing the reload config and it still didn't work. Restarting the server was also done as well.

**Comment by itzJOHv** [comment]
Does your `chat.format` contain `[usertag]` placeholder?

**Comment by arsondog** [comment]
Yes. Why.

**Comment by itzJOHv** [comment]
> Why.

PowerRanks uses that placeholder for Deluxetags tag.

**Comment by arsondog** [comment]
It still doesn't work with that there?

**Comment by arsondog** [comment]
Closing this because the problem was Power ranks was on Bukkit and the Deluxetags was on Spigot. Transferred Powerranks over to Spigot.
