### ISSUE TITLE
Recent PowerRanks versions breaking other permission providers?

### ISSUE THREAD

**Issue by LlmDl** [PowerNetworkHub/PowerRanks#66]
Over the course of the last month I have had more and more PowerRanks users come to the Towny discord to say that our permissions do not work.

Towny has a built-in permission plugin which gives out permission nodes to players based on their towny role: nomad, town member, town mayor, nation leader, nation member, etc.

It supplies Bukkit superperms with permission nodes to each player while they are in Towny-enabled worlds. This system has worked quite well for us for years. Admins don't have to set up permission nodes and the system "just works".

For each admin with this mysterious issue the common element has been a recent version of PowerRanks: v1.10.5R2.

I have not gone over all of your commits but I suspect something has changed which has resulted in your plugin overwriting other plugins' additions to a player's nodes. 

This issue plus the additional issue in #60 have proven to be a substantial roadblock for Towny admins wanting to use PowerRanks.

**Comment by svenar-nl** [comment]
I've looked into the reported issue regarding PowerRanks affecting Towny permissions.
After investigation, I've identified and resolved the problem. The fix will be included in the upcoming release, PowerRanks v1.10.8.

**Comment by LlmDl** [comment]
Nicely done.
