### ISSUE TITLE
Powerranks won't show up on plugin list

### ISSUE THREAD

**Issue by TechnicalityMods** [PowerNetworkHub/PowerRanks#67]
When I put the plugin into my server and restart it, It doesn't show up on my list when i do /pl. Please help me out, as I need this for my smp asap

**Comment by itzJOHv** [comment]
please send output of `/version` command

**Comment by TechnicalityMods** [comment]
![image](https://user-images.githubusercontent.com/91298884/190634412-1eac41a6-dec9-43bb-a32e-066cfcb769a5.png)
