### ISSUE TITLE
PowerRanks allows crashing easily on servers.

### ISSUE THREAD

**Issue by VoidedGorilla** [PowerNetworkHub/PowerRanks#84]
Some backstory:
I use powerranks for Ranks, and perms, the main competitor in my opinion is LuckPerms, Luckperms is confusing and causes lag on servers, so I use powerranks because it's simpler and better (very much 9/10) But there's a problem with PowerRanks.

Main Issue:
There's a way to crash an entire server if they use powerranks and doesnt have a fix for it. The method lags out the server by sending packets at powerranks causing the server to lag incredibly and it causes the server to crash. Anyone can do this, and this is an issue that reoccurs in my server, people crash it, they use alts, and vpns. It would be great if this issue could be fixed as it's a MAJOR FLAW in PowerRanks.

Sincerely, ematthew1.

**Comment by svenar-nl** [comment]
Do you have some more information on how that process looks like?
In order to fix this we need more information about how that is happening.

Thank your for your time and letting us know about this issue.

**Comment by VoidedGorilla** [comment]
> Do you have some more information on how that process looks like? In order to fix this we need more information about how that is happening. A timings/spark log and a server log where the issue happens can help a lot.
> 
> Thank your for your time and letting us know about this issue.

Thats the issue, there's no logs that appear when the crash occurs. Simply to put it, the server just lags out like crazy and automatically shuts down after 5 to 3 minutes of lag. I do have a client that has the crasher method though, if that helps?

**Comment by VoidedGorilla** [comment]
sorry bout that, kinda new to github...

**Comment by svenar-nl** [comment]
Anything that you can provide will help

**Comment by ProJakob** [comment]
Hey, I have access to the client providing the crasher. I'm still not sure if it actually is PowerRanks causing the problems, but I'm confident it is as the only servers that crashed were using PowerRanks.

**Comment by svenar-nl** [comment]
Can you give me more information about the client / crashed. I would like to obtain it and use it for testing as well in order to narrow down the issue

**Comment by ProJakob** [comment]
The client is a fabric mod in the form of a meteor addon. I may not quickly respond here but my discord is just_jakob.
I would rather not put the jar here on github as that may just cause even more damage.

**Comment by ProJakob** [comment]
The crash works by sending a lot of tab completion requests to the server. But I saw that PowerRanks doesn't use generic Tab Completion Events. So it's unlikely that it's actually a cause of PowerRanks and instead of another Plugin that is common around all of these servers.

**Comment by VoidedGorilla** [comment]
> The crash works by sending a lot of tab completion requests to the server. But I saw that PowerRanks doesn't use generic Tab Completion Events. So it's unlikely that it's actually a cause of PowerRanks and instead of another Plugin that is common around all of these servers.

yes but any server that uses luckperms instead of powerranks, it doesnt crash.

**Comment by ProJakob** [comment]
> > The crash works by sending a lot of tab completion requests to the server. But I saw that PowerRanks doesn't use generic Tab Completion Events. So it's unlikely that it's actually a cause of PowerRanks and instead of another Plugin that is common around all of these servers.
> 
> yes but any server that uses luckperms instead of powerranks, it doesnt crash.

This is due to PowerRanks having a slow function which caused freezes and lag spikes due to FastAsyncWorldEdit overusing the function. We optimized the function to be about 2-3x faster

**Comment by svenar-nl** [comment]
The improved function is on average 382% faster.
This issue will be closed once PowerRanks releases with this fix.

**Comment by TheMeteorGuy** [comment]
> Hey, I have access to the client providing the crasher. I'm still not sure if it actually is PowerRanks causing the problems, but I'm confident it is as the only servers that crashed were using PowerRanks.
> 
> EDIT: I'm also probably gonna commit some testing later this day when i find time to.

( u are the owner of it )
