### ISSUE TITLE
Rank Prefix Shows Up Twice Instead of Once

### ISSUE THREAD

**Issue by Lynxmountain** [PowerNetworkHub/PowerRanks#92]
**Issue:**
Rank Prefix Shows up twice in username. I have attempted to uninstall and reinstall and it did not fix it. 
I do not know if the Suffix also has this problem or not, I have not attempted to use the suffix.

**To Reproduce**
- Unknown

**Expected behavior**
Expect 1 Rank Prefix Before the player Name but am getting 2 identical rank prefixes.

**Screenshots**
<img width="496" alt="Screen Shot 2023-10-26 at 3 58 48 PM" src="https://github.com/PowerNetworkHub/PowerRanks/assets/125523629/7fab819c-0861-4074-8924-37e98ffa2717">
<img width="384" alt="Screen Shot 2023-10-26 at 4 05 16 PM" src="https://github.com/PowerNetworkHub/PowerRanks/assets/125523629/ece030a6-6d69-4748-b3db-b13e89c0aa37">

**Additional Info**
Note: The Both Words Are the Prefix, I do not have a Suffix Or UserTag Set.
This Issue only seems to occur with the chat, not in Tab.

 - OS: [macOS]
 - Server type [Spigot/Bukket]
 - Minecraft Version [1.20.2]
 - PowerRanks version [v1.10.8R2]

**Comment by djohts** [comment]
You probably have EssentialsXChat installed. You can either configure or remove it, that would fix your issue.

**Comment by Lynxmountain** [comment]
> You probably have EssentialsXChat installed. You can either configure or remove it, that would fix your issue.

ya just figured it out but thank you. have not tested it yet but i think that is what was causing the issue.
