### ISSUE TITLE
New usernames not being updated in PowerRanks

### ISSUE THREAD

**Issue by Snackii** [PowerNetworkHub/PowerRanks#94]
**Describe the bug**
Users who change their usernames seem to not have their profiles updated in PowerRanks. Executing a command for them using their current names returns an error stating the command failed. However, executing the same command but using their previous usernames successfully executes the command. This can be problematic when trying to automate some tasks, such as rank ups. This issue requires looking up a user's previous name and then manually executing commands for them.

**To Reproduce**
1. Have a user connect to the server
2. Have the same user change their username
3. Have the user reconnect to the server
4. Attempt to execute a command using their current username

**Expected behavior**
The user profile should be updated in the PowerRanks files, and commands should be able to be executed using a player's current username.

**Desktop (please complete the following information):**
 - Server type: Paper
 - Minecraft Version: 1.20.2
 - PowerRanks version: 1.10.9

**Comment by svenar-nl** [comment]
Thanks for notifying me about this issue, I've confirmed this to be an issue and a fix will be available in the next release

**Comment by svenar-nl** [comment]
This issue has been fixed in PowerRanks v1.10.9R2 https://modrinth.com/plugin/powerranks/version/1.10.9R2
